### ISSUE TITLE
Please "git tag" your RAKU modules with it's versions

### ISSUE THREAD

**Issue by AntonOks** [bbkr/JSON-RPC#38]
Can you please "GIT TAG" your RAKU modules with it's version, similar and at the same time you maintain it's **_"version": "x.y.z"_** in your `META6.json` file?

I was told, this will happen "for free" going forward with mi6 anyhow, but for now it would be great if you spend those 2 seconds already now :)

"Tagging" is generally highly appreciated in regards to "reproducible builds" and here especially for the ["Rakudo Star" modules](https://github.com/rakudo/star/blob/master/etc/modules.txt)

THANK YOU!

**Comment by bbkr** [comment]
Hi

No problem. I'll add it in about 8h when I'm back from $dayjob.

BTW: This module is one of the earliest ones in Rakudo Star distribution, however I would not mind if it gets retired. JSON::RPC today has marginal popularity. And because of that now module is in maintenance-only mode for years. This is mediocre quality old code, written back in Parrot VM times.

**Comment by bbkr** [comment]
1.0.5 tagged
